// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewSchedule struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Schedule struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
